### ISSUE TITLE
Add looks-same to benchmarks

### ISSUE THREAD

**Issue by Yeti-or** [dmtrKovalenko/odiff#10]
<strike>https://github.com/gemini-testing/png-img</strike>
https://github.com/gemini-testing/looks-same

**Comment by dmtrKovalenko** [comment]
AFAI It is a wrapper around libpng, which is not doing the comparison.

**Comment by Yeti-or** [comment]
@dmtrKovalenko you are right: https://github.com/gemini-testing/looks-same
