### ISSUE TITLE
There is a difference in speed between version 2 and version 3 for the worse

### ISSUE THREAD

**Issue by Mauladen** [dmtrKovalenko/odiff#101]
Good afternoon, I use lost-pixel, it uses version 2.6.1 by default, from which I got a speed in the region of 2.2 - 2.5 seconds on a very large sample of launches, since all this starts every time in CI, after forcefully specifying version 3.0.1, I started getting the result in 3.5 - 3.6 seconds

I read that you, on the contrary, improved the algorithm and speed in version 3, but something is wrong in this case, perhaps something is required from the developers of lost-pixel so that version 3.0.1 shows a better result than the 2.6.1?

**Comment by dmtrKovalenko** [comment]
Can you please attach an example of image that generates worse results with v3

**Comment by Mauladen** [comment]
> Can you please attach an example of image that generates worse results with v3

Unfortunately, I can't do this, attach images due to my company's policy, but there is nothing unique about them, this is a UI Kit that is being developed in Storybook, the screenshot resolution is 1200x720 and there are many different components, as an example, you can look at any open source UI Kit

I understand that if I could provide you with all the images, then you would be able to better understand the problem and fix it, but unfortunately I do not have such an opportunity and I can only give feedback related to speed
