### ISSUE TITLE
Odiff not working in windows x64

### ISSUE THREAD

**Issue by c3-iajimenez** [dmtrKovalenko/odiff#103]
I'm trying to run some visual tests using odiff but I am getting the following error:
![image](https://github.com/user-attachments/assets/17de90a5-7209-4b7b-a138-ecf9c1ef0153)
I get the same error when trying to run the odiff.exe.

**Comment by Fihy** [comment]
Same here.

**Comment by dmtrKovalenko** [comment]
Okay this is becoming really interesting 😰

Could you provide as much info as possible. The output of odiff --version and help how did you install and any other information. Thanks!

**Comment by c3-iajimenez** [comment]
@dmtrKovalenko I am not able to run the odiff cli, it is not recognized by my powershell once I install the npm command. On mac, I am unable to use the cli, but I am able to run the odiff node api. 

I did attempt to run the .exe odiff file that is located in the bin folder of the odiff but i get the same error.  I tried updating odiff but that did not work either. I am currently in odiff version 3.0.0

**Comment by dmtrKovalenko** [comment]
![IMG_9280](https://github.com/user-attachments/assets/6079612a-04c0-4ffa-b958-3b39c9e39612)

yeah I finally found a windows machine. Debugging

**Comment by c3-iajimenez** [comment]
@dmtrKovalenko  any update with this?

**Comment by dmtrKovalenko** [comment]
Working on this, unfortunately it needs a lot of rework because this is the problem with build system not with the code. 

Meanwhite you can use 2.6.3 which is working perfectly fine on windows

**Comment by c3-iajimenez** [comment]
@dmtrKovalenko  thanks for the update ! Will switch to 2.6.3

**Comment by dmtrKovalenko** [comment]
fixed in 3.1.0 https://github.com/dmtrKovalenko/odiff/releases/tag/v0.3.1 🎉
