### ISSUE TITLE
I found some problems with the build

### ISSUE THREAD

**Issue by Mauladen** [dmtrKovalenko/odiff#107]
After upgrading to the current version from version 3.0.1, something broke

In the release, all files have .exe
![](https://github.com/user-attachments/assets/938f4d39-683e-4fd7-9b5b-d9ccfd6e14dd)

Also appeared in yarn.lock .exe
![](https://github.com/user-attachments/assets/ba3aa440-0b63-440b-95a7-95a87188ee8d)

Apparently, because of all this, an error occurs, unfortunately nothing is output to the console

**Comment by dmtrKovalenko** [comment]
could you please provide some steps to reproduce the behavior

**Comment by Mauladen** [comment]
I also have a question, could you add linux-arm support?

**Comment by dmtrKovalenko** [comment]
This is a nice question. Once this: https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/  will be available publicly I can do it in a second. Now it will need a self hosted runner.

**Comment by dmtrKovalenko** [comment]
Could you try to reinstall the package and sent me all the output you see. Like if you'll run the `npx odiff --version`

**Comment by Mauladen** [comment]
> Could you try to reinstall the package and sent me all the output you see. Like if you'll run the `npx odiff --version`

The result of this command is 3.0.0
It seems that everything works correctly this way

**Comment by dmtrKovalenko** [comment]
Ideally you should upgrade to 3.1.0. Likely you are using some staled cached node module

**Comment by Mauladen** [comment]
I can say that most likely there is no problem with bin, but I use lost-pixel and so an error occurs, it is not displayed, so I can't say exactly what the problem is, after studying the code I saw that the [`compare`](https://github.com/lost-pixel/lost-pixel/blob/f25c25065d8d663383bb7e8ef1a9ec3390b2ae27/src/compare/compare.ts#L102) function is used there for comparison, perhaps an error occurs in it but this is not 100% information

I'd like to really understand what breaks after upgrading from version 3.0.1.

**Comment by dmtrKovalenko** [comment]
but the latest version is 3.1.0

**Comment by olegafx** [comment]
`linux-arm64` build is missing. It's working great with `v3.0.1` but fails with `v3.1.1`
