### ISSUE TITLE
Iterate over y-coordinates in outer loop

### ISSUE THREAD

**Issue by laino** [dmtrKovalenko/odiff#12]
Had a quick look at this, and it appears the tool is iterating over x-coordinates in the outer loop.

If your image library's memory layout is anything like most others out there, this isn't the most CPU/memory friendly way to go about it.

**Comment by dmtrKovalenko** [comment]
Yes thanks. That’s definitely makes sense

Best regards,
Dmitriy Kovalenko

13 дек. 2020 г., в 06:45, Nils Kuhnhenn <notifications@github.com> написал(а):

﻿

Had a quick look at this, and it appears the tool is iterating over x-coordinates in the outer loop.

If your image library's memory layout is anything like most others out there, this isn't the most CPU/memory friendly way to go about it.

**Comment by dmtrKovalenko** [comment]
Fixed in the v2
