### ISSUE TITLE
[Feature] Combine reference and diff images and add custom color parameter

### ISSUE THREAD

**Issue by viraxslot** [dmtrKovalenko/odiff#15]
Hi,
Problem: sometimes diff image is really small and it's hard to understand the difference between current and reference images.
Proposal: allow to generate diff2 image that add diff-mask above the reference image;
Proposal 2: mark such differences somehow if there are small (circle around them or so);

Of course, if the reference image has a lot of red it could be a problem (because diff-image is always red), so we need also a parameter for diff-image color.

Thanks in advance :)

**Comment by dmtrKovalenko** [comment]
Does `diffImage` param is what you need? 

```ts
type ODiffOptions = {
  /** Output full diff image. */
  diffImage: boolean;
  /** Do not compare images and produce output if images layout is different. */
  failOnLayoutDiff: boolean;
  /** Color difference threshold (from 0 to 1). Less more precise. */
  threshold: number;
};

declare function compare(
  basePath: string,
  comparePath: string,
  diffPath: string,
  options?: ODiffOptions
): Promise<
  { match: true } | { match: false; reason: "layout-diff" | "pixel-diff" }
>;

```

**Comment by viraxslot** [comment]
@dmtrKovalenko sorry, my bad, I didn't notice this option. It works fine with `diffImage: true`, thanks.
So, I can keep only custom color feature request :) 

Also it would be nice to set only one option, because all are mandatory now.
