### ISSUE TITLE
The benchmark should say "Pixelmatch + pngjs" to better reflect the code compared. 

### ISSUE THREAD

**Issue by p01** [dmtrKovalenko/odiff#22]
The benchmark in the README.MD mentions "Pixelmatch", and shows a graph comparing Odiff, ImageMagick and Pixelmatch. 

However the benchmark includes the PNG decoding, image diffing, and finally PNG encoding of the diff image. Given the resolution of the images, the PNG codec will take a significant share of the time.

It would be more fair to say "Pixelmatch + pngjs"  together.

**Comment by dmtrKovalenko** [comment]
Yes and no. Pixelmatch for NodeJS by definition needs to be used together with decoder (at least for base image). But if you wish feel free to make PR changing readme
