### ISSUE TITLE
Darwin arm64

### ISSUE THREAD

**Issue by n7olkachev** [dmtrKovalenko/odiff#23]
Could you provide darwin arm64 build?

**Comment by dmtrKovalenko** [comment]
Unfortunately no :( 
it is so expensive

**Comment by n7olkachev** [comment]
Dockerfile or some instructions on how to compile it?

**Comment by n7olkachev** [comment]
Docker is capable of multiarch builds so it is the easiest solution.

**Comment by dmtrKovalenko** [comment]
OCaml cannot in cross compilation, and there is no darwin arm OS provided by azure pipelines :(

**Comment by n7olkachev** [comment]
You don't need ocaml to be capable of cross compilation. You can run docker build with another arch via 'docker build --platform' or 'docker buildx'.

Try to describe your build process in a Dockerfile. There is a good chance that it will work for arm architecture. I can help you with CI/CD part, but I can't do it without knowledge of how to build your project.

As you know, arm architecture is used by M1 macs, so you will need to find a solution for this problem eventually.
