### ISSUE TITLE
NodeJS demo code?

### ISSUE THREAD

**Issue by tomByrer** [dmtrKovalenko/odiff#25]
I can't find any demonstration code how to use this lib anywhere.  Doesn't help that both NPM & Oracle have packages of the same name....

TIA :)

**Comment by dmtrKovalenko** [comment]
There is a nodejs demo code in readme.md. Make sure that package name is odiff-bin

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/odiff#nodejs
