### ISSUE TITLE
Make diff code available as a separate package

### ISSUE THREAD

**Issue by eWert-Online** [dmtrKovalenko/odiff#28]
Would you be open to the idea of publishing the diff code (everything located under src) to opam? 
Or at least separate it into its own opam library, so you can install it using esy without installing all requirements needed for the io part.

**Some background:**
I am currently working on a snapshot testing library, using odiff. 
Right now, installing odiff with esy also installs everything needed for the io package, which I don't use.

So it would be great to be able to just install the diff part.

**Comment by dmtrKovalenko** [comment]
Makes a lot of sense, I was thinking about this initially. Just need to prepare infrastructure for publishing as package

> Sorry I need to dive into anti-aliasing PR. Will try to get this done today

**Comment by eWert-Online** [comment]
Do you already have some solution for this in mind? 

I don't know of an easy way to have a monorepo setup with esy.  
So my guess would be that completely separating them into their own esy / npm packages would be the easiest way of achieving this.

**Comment by dmtrKovalenko** [comment]
I think we already have everything for publishing it. There are 3 packages in monorepo 

1) bin – cli interface
2) io – IO modules that includes code for reading and parsing an image
3) src – odiff package that actually implements the 

What you probably are looking for is to publish src package to OPAM

**Comment by eWert-Online** [comment]
Yes, publishing just src would be great. I was thinking of a way to do it with esy, but using opam would make it easier of course. 

> so maybe we need to unify IO and src packages

I would try to avoid that. The IO package generates pretty much all the dependencies. So if I write an ocaml program which implements its own IO, I would get all the dependencies but would not use any of them. 
Keeping them separate would be better in my opinion. You could still publish them as two separate opam packages (`odiff` and `odiff.io` for example).
