### ISSUE TITLE
Anti-aliasing support

### ISSUE THREAD

**Issue by pashidlos** [dmtrKovalenko/odiff#3]
In order to ignore noise from anti-aliasing would be useful to implement it's support 

example from pixelmatch 
https://github.com/mapbox/pixelmatch/blob/2b03b635cffb9525bcefee4cc7329f98e375cff5/index.js#L93

paper:
https://www.researchgate.net/publication/234126755_Anti-aliased_Pixel_and_Intensity_Slope_Detector

**Comment by Klaster1** [comment]
Any heads up on how different antialiasing will be when compared to pixelmatch? Recently, I finally covered canvas chart generation in my app with tests using pixelmatch and don't like that tests are useless unless you always run them in the same environment (Docker/VM) or crank up the thresholds.

**Comment by dmtrKovalenko** [comment]
I am going to investigate the specialised anti-aliasing detection alghoritms and will pick up the best one (even if it is harder and slower). 

I am going to work on this on the next week (now busy with conference)
