### ISSUE TITLE
odiff-bin. Diff image size is not resulted in expected `layout-diff` response

### ISSUE THREAD

**Issue by pashidlos** [dmtrKovalenko/odiff#43]
<img width="1425" alt="1" src="https://user-images.githubusercontent.com/5182956/123210793-30f8e680-d4cb-11eb-98ea-ce394f6b9410.png">

code to reproduce: 
https://github.com/pashidlos/image-compare-tryouts/blob/odiff-diffLayout/src/odiff.js

**Comment by dmtrKovalenko** [comment]
You need to pass specific flag `failOnLayoutDiff`

**Comment by pashidlos** [comment]
I did, but it works only if I compare completely different images (ex  "1.png" vs "diffLayout2.png" it works)
you could find images and code inside the repo

```js
const odiff = require("odiff-bin");
const {getImagePath} = require("./utils");

(async () => {
  const result = await odiff.compare(
    getImagePath("diffLayout1.png"),
    getImagePath("diffLayout2.png"),
    getImagePath("diff.png"),
    {
      failOnLayoutDiff: true
    }
  );

  console.log(result);
})();
```

**Comment by eWert-Online** [comment]
It currently only fails if the width AND height are different from the original image. 
(https://github.com/dmtrKovalenko/odiff/blob/main/src/Diff.re#L98)

I also noticed this some time ago, but thought it maybe was intended.
It would be an easy fix though, if it isn't intended 😄

**Comment by dmtrKovalenko** [comment]
Ohh that is definitely a mistake
