### ISSUE TITLE
odiff: internal error, uncaught exception

### ISSUE THREAD

**Issue by CharalamposSam** [dmtrKovalenko/odiff#66]
Hello, I'm using odiff with cypress. Everything is working fine, but only in Jenkins, I'm getting the following error in **some** scenarios (not in all scenarios):

CypressError: `cy.task('compare')` failed with the following error:

 > odiff: internal error, uncaught exception:
    Failure("Can not save the output :(")

Do you have any idea why is this happened?

The whole error:
![image](https://user-images.githubusercontent.com/44839448/193750204-e34c5490-d068-426b-936e-5788ad0ede68.png)

*_When the scenarios run locally with docker, this error never appeared. I face this error only in Jenkins_

**Comment by dmtrKovalenko** [comment]
That is really weird. This exception comes from c function `fopen` which creates a file for writing and if it crashes it means that the system rejects from writing a new file. 

It can be a whole bunch of reasons, we need to make sure to correctly show it, here are some on top of my mind: 

1. System rejects /n in filenames
2. Permission issue
3. Not enough disk space 

I'll do my best to implement displaying the proper error message for this error as soon as possible

**Comment by eriviere-b** [comment]
For your information, the same issue appears from the command line on Macbook Pro with Apple M1 if I do not specify the output filename:
![image](https://user-images.githubusercontent.com/115537789/199690993-cace0314-af1b-46d1-bc93-74ee78216fae.png)

**Comment by dmtrKovalenko** [comment]
I also have the MacBook Pro m1 and have no issues, would be perfect if you can create a simple reproduction when it fails

**Comment by dmtrKovalenko** [comment]
Closed by 4ccc1affdf7d06410371e41f985d25daead79aac
