### ISSUE TITLE
Update peer dependencies related Cypress 

### ISSUE THREAD

**Issue by MykolaKozub** [dmtrKovalenko/odiff#67]
Right now the peerDependencies lists

  "peerDependencies": {
    "cypress": "10.0.3"
  }
so there is a dependency warning if you are using a newer major version of cypress 10.7.0
I would propose changing it to ^n if there are no issues.

Awesome tool - thanks so much!

**Comment by dmtrKovalenko** [comment]
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/16926049/200680617-e24d3672-5c2a-418d-a7cd-ba8a18582e19.png">

**Comment by MykolaKozub** [comment]
my apologies thanks, Dmitry! i added 'cypress-odiff' and did not notice that it is different, thanks for a super quick answer
