### ISSUE TITLE
[bug] Image comparaison issue

### ISSUE THREAD

**Issue by jsfez** [dmtrKovalenko/odiff#72]
Hello Dmitriy,

Your project seems amazing and I would like to use it but I found an issue in image comparison.

It seems that odiff can't see the differences between this images. 

![rect](https://user-images.githubusercontent.com/15954562/206850879-06789e49-659c-4390-996f-d50c81006476.png)

![rect-new](https://user-images.githubusercontent.com/15954562/206850881-e5529ef4-c467-40e9-8629-cdbeff2ca7b9.png)

**Comment by dmtrKovalenko** [comment]
Wow that is very unfortunate! Will take a look into this issue today

**Comment by jsfez** [comment]
Thank a lot

**Comment by dmtrKovalenko** [comment]
![diff](https://user-images.githubusercontent.com/16926049/206853134-cfcc4409-ba1d-43b1-b81d-85a32a7a75d0.png)

In your case you should pass the -t 0 it looks like the algorithm that we are using treats these 2 colors very similar and the default threshold omits this from the diff

**Comment by jsfez** [comment]
Thank you for your help and reactivity!
For archives, I set the threshold to 0.7.

Otherwise, I've seen that you have worked for Material UI. So you may have used [Argos](https://www.argos-ci.com/) for automatic visual testing. 
We are working on a complete rework, and if the tests are conclusive, we will use Odiff instead of ImageMagick.
