### ISSUE TITLE
Feature request: Add option to specify acceptable percentage of different pixels

### ISSUE THREAD

**Issue by A-CGray** [dmtrKovalenko/odiff#77]
I am trying to use odiff in the CI pipeline of a plotting tool I maintain called [NicePlots](https://github.com/mdolab/niceplots) to test that the images output by our examples remain consistent. We are running into the issue that, even using the `--antialiasing` command line option, we still have images differing on very small numbers of pixels due to what I assume are slight differences in anti-aliasing on different systems.

Here's an example from one of our recent CI runs:

### Reference image

![doumont-light_style_demo_reference](https://user-images.githubusercontent.com/20371123/214398466-c8a9f16d-b8fb-4e7a-a3d5-270bfab42f89.png)

### Test image

![doumont-light_style_demo](https://user-images.githubusercontent.com/20371123/214398520-7ce6a3a3-d0cb-475c-a6f6-d406d6f38ae7.png)

### Difference

```shell
odiff --aa --threshold=0.1 --dm doumont-light_style_demo_reference.png doumont-light_style_demo.png doumont-light_style_demo-diff.png
Failure! Images are different.
Different pixels: 386 (0.003490%)
```

![doumont-light_style_demo-diff](https://user-images.githubusercontent.com/20371123/214399255-ffb3efa1-8bee-48e5-b51a-1c45eb614bdd.png)

In our case, these minor differences are not the kind of thing we're looking to catch with our tests. We tried playing around with the `--threshold` option but found we had to make it impractically high to get past these issues.

It would be extremely useful to be able to specify that a certain percentage of differing pixels (e.g <= 0.01%) is acceptable, by adding a command line option like `--tolerance=0.01`.

**Comment by Klaster1** [comment]
Second this, I was looking forward to using odiff for a while, but to my dismay discovered that even a dockerized browser generates very subtle text rendering differences in CI vs local, which odiff picks up even with `antialiasing: true`.

**Comment by dmtrKovalenko** [comment]
This is a classic problem of any VR which could be solved by percentage detection, but I would recommend to run this type of checks always in one docker container instead. 

If you still want to use percentages you can read the output of the odiff. It returns pixels count and percentage

**Comment by A-CGray** [comment]
Hey Dmitry, thanks for responding to this.

I'm using the odiff CLI and just judging whether the images match based on the exit code, see [here](https://github.com/mdolab/niceplots/blob/cb1957d32925c0e8f1ca4f32676074ec3699fe2e/examples/ImageComparisonTest.sh#L28-L31)

From @Klaster1's comment it seems that running the tests in a docker container is not guaranteed to fix this issue. I guess parsing the odiff output would work but that seems like a very complex solution. 

The solution I had in mind would be to add a `tolerance` command line option, so I can call `odiff --antialiasing --tolerance=0.1 image1.png image2.png` to tell odiff to exit with a 0 code as long 0.1% or less of the pixels are different between the images.

As far as I can see, this would only require some very simple changes to the logic [here](https://github.com/dmtrKovalenko/odiff/blob/aa5309b4b4b33cf8089b712995663ab9bb3165e5/bin/Main.re#L66-L74) to `exit 0` when `diffPercentage <= tolerance`  instead of `diffCount == 0`.

**Comment by dmtrKovalenko** [comment]
That is reasonable and I can do that quickly or feel free to open PR. 

In the mean time there is also an option called --parsable-output which makes output a simple string separated by values which will be very easy to parse even with sh. But I'll try to add that asap

**Comment by A-CGray** [comment]
Awesome, thanks @dmtrKovalenko ! I would have tried implementing something but have no experience with reason/OCaml. I will test out that parsable output option in the meantime

**Comment by A-CGray** [comment]
For future reference, I was able to implement some logic in bash to achieve this check outside odiff:

https://github.com/mdolab/niceplots/blob/b23b4d85ae582bb653637316ce1c2c9c0f682028/examples/ImageComparisonTest.sh#L29-L42
