### ISSUE TITLE
Screenshot's resolution varies on different screen resolution.

### ISSUE THREAD

**Issue by Manishh09** [dmtrKovalenko/odiff#84]
By default the screenshot which are taken are having the resolution of 1503x791 px ( When my PC resolution is 1920x1080)
And if we reduce display resolution in PC and the resolution of screenshots taken is varying.
Is there any way to fix this and make this independent of screen resolution.
Thanks!

**Comment by dmtrKovalenko** [comment]
I don't think so because the goal is to validate every pixel. 

What you should do is to run your app on a specified resolution, so the screenshot you are making is always same. 

Ideally run everything in isolation. E.g. docker container.

**Comment by Manishh09** [comment]
Thanks for swift reply Dimitriy!

Do you mean , whether the app should run on a specified PC resolution or how?
Could you please clarify this. 

Thank you!

**Comment by dmtrKovalenko** [comment]
Either this or change the size of the window that is taking screenshot. 

Environment for visual regression should be as isolated as possible.
