### ISSUE TITLE
How do I draw different pixels to the grayscale image of the original image?

### ISSUE THREAD

**Issue by lvsejunzhuang** [dmtrKovalenko/odiff#89]
How do I draw different pixels to the grayscale image of the original image?Because I think the difference pixels look clearer in grayscale images.

**Comment by dmtrKovalenko** [comment]
Sorry for long answer but there is no way. This is a part of why odiff is so fast -- no reason to mutate every pixel of original image. But you can still export the mask, manually display expected image as grayscale using user's gpu and display the diff mask on top
