### ISSUE TITLE
hang on when run macbook mini

### ISSUE THREAD

**Issue by wanghaisheng** [dmtrKovalenko/odiff#9]
(base) wenke@wenkedeMac-mini odiff-e7f41c97 % odiff  20201123/N_0_2006255981_B.bmp 20201123/N_0_2006255981_T.bmp  1.png

hang on there with no result at all , two image are all 300kb
download source code and run npm install ,rename bin/ODiffBin to odiff ,add this bin path to zsh

**Comment by dmtrKovalenko** [comment]
Not sure what the problem do you have. Can you please be more descriptive? Thanks.

**Comment by wanghaisheng** [comment]
i. got no result. when run above command .all input image are not huge size,  my computer is fine.

**Comment by dmtrKovalenko** [comment]
You need 3rd required parameter it's 1st. But it will throw an error if only 2 provided. 

How did you installed?

**Comment by wanghaisheng** [comment]
this is 3 para 
```
 20201123/N_0_2006255981_B.bmp 20201123/N_0_2006255981_T.bmp  1.png
```

**Comment by wanghaisheng** [comment]
if you mean how did i install odiff
```
 download source code and run npm install ,rename bin/ODiffBin to odiff ,add this bin path to zsh
```

**Comment by dmtrKovalenko** [comment]
@wanghaisheng if you are running the binaries – there is no `npm install` required. If you want to use npm you can do the following:

```sh
npm install -g odiff-bin
odiff --help # runs and shows help
```

**Comment by wanghaisheng** [comment]
@dmtrKovalenko  no luck at all
```
(base) wenke@wenkedeMac-mini ~ % odiff --help # runs and shows help
odiff: option `--help': invalid value `#', expected one of `auto', `pager',
       `groff' or `plain'
Usage: odiff [OPTION]... [BASE] [COMPARING] [DIFF]
Try `odiff --help' for more information.
(base) wenke@wenkedeMac-mini ~ % cd ~/Downloads/odiff-e7f41c97 
(base) wenke@wenkedeMac-mini odiff-e7f41c97 % ls
20201123		lcs-image-diff-test.js	package.json
_esy			lib			pixelmatch-test.js
bin			man			sbin
doc			node_modules		share
etc			package-lock.json	toplevel
(base) wenke@wenkedeMac-mini odiff-e7f41c97 %  odiff 20201123/N_0_2006255981_B.bmp 20201123/N_0_2006255981_T.bmp 1.png
```

**Comment by dmtrKovalenko** [comment]
As far I see it works for you.
