### ISSUE TITLE
npm has Version 2.6.1 but there is no 2.6.1 in this repo

### ISSUE THREAD

**Issue by alextreppass** [dmtrKovalenko/odiff#90]
Hello, we are looking to sanity check the post-install scripts and binaries — we are wanting to try out [Lost Pixel](https://www.lost-pixel.com/) which uses odiff-bin.

They specify version `2.6.1` which exists on npm, but not here in this project apparently.

I've diffed the release tars via `npm pack odiff-bin@2.6.0` / `npm pack odiff-bin@2.6.1` and the only changes are the version numbers in the package.json and the platform binary files (darwin, linux, windows-x64)

@dmtrKovalenko any chance you have information on the 2.6.1 release please?

Thanks

**Comment by dmtrKovalenko** [comment]
I think they might use different version for simplicity of installing patched version on lambdas.

**Comment by dmtrKovalenko** [comment]
Nevermind previous comment. The versions are the same just release was not created. They both used 2.6.1 in fact https://www.npmjs.com/package/odiff-bin

**Comment by d-ivashchuk** [comment]
@alextreppass if you need any help with lost pixel, would be more than happy to give you a hand!

**Comment by alextreppass** [comment]
Thanks!

**Comment by alextreppass** [comment]
@d-ivashchuk one thing that we're worried about before adopting is this https://github.com/lost-pixel/lost-pixel/issues/377 if you could take a look thank you
