### ISSUE TITLE
No prebuilt downloads for `3.0.0` release

### ISSUE THREAD

**Issue by mattyclarkson** [dmtrKovalenko/odiff#97]
No downloadable prebuilt binaries archives are available on the [release](https://github.com/dmtrKovalenko/odiff/releases/tag/v3.0.0). Will they be added to future `3.x` releases?

**Comment by dmtrKovalenko** [comment]
Ohh shoot this is a mistake, yes I need to make a new release soon anyway. I’ll make sure to automate that

**Comment by one2123** [comment]
Hello, I was trying to build the latest version and ran into some issues. I dont have any experience in ocaml/dune so can you provide some build instructions please.

**Comment by dmtrKovalenko** [comment]
Fixed and automated starting from 3.0.1 release
